home:
    path: /
    controller: App\Controller\DefaultController::indexAction

project:
    path: /project
    controller: App\Controller\ProjectController::projectAction


dashboard:
    path: /admin/dashboard
    controller: App\Controller\Admin\DashboardController::boardAction

addProject:
    path: /admin/addProject
    controller: App\Controller\Admin\DashboardController::addProjectAction

projectAdmin:
    path: /admin/project
    controller: App\Controller\Admin\DashboardController::projectAction

modProject:
    path: /admin/{id}/modProject
    controller: App\Controller\Admin\DashboardController::modProjectAction

supProject:
    path: /admin/{id}/supProject
    controller: App\Controller\Admin\DashboardController::suppProjectAction

skillAdmin:
    path: /admin/skill
    controller: App\Controller\Admin\DashboardController::skillAction

addSkill:
    path: /admin/addSkill
    controller: App\Controller\Admin\DashboardController::addSkillAction

modSkill:
    path: /admin/{id}/modSkill
    controller: App\Controller\Admin\DashboardController::modSkillAction

supSkill:
    path: /admin/{id}/supSkill
    controller: App\Controller\Admin\DashboardController::supSkillAction

technoAdmin:
    path: /admin/technoAdmin
    controller: App\Controller\Admin\TechnoController:technoAction

addTechno:
    path: /admin/addTechno
    controller: App\Controller\Admin\TechnoController:addTechnoAction

modTechno:
    path: /admin/{id}/modTechno
    controller: App\Controller\Admin\TechnoController:modTechnoAction

supTechno:
    path: /admin/{id}/supTechno
    controller: App\Controller\Admin\TechnoController:supTechnoAction
