home:
    path: /
    controller: App\Controller\DefaultController::indexAction

project:
    path: /project
    controller: App\Controller\ProjectController::projectAction


dashboard:
    path: /admin/dashboard
    controller: App\Controller\DashboardController::boardAction

addProject:
    path: /admin/addProject
    controller: App\Controller\DashboardController::addProjectAction

projectAdmin:
    path: /admin/project
    controller: App\Controller\DashboardController::projectAction

modProject:
    path: /admin/{id}/modProject
    controller: App\Controller\DashboardController::modProjectAction

supProject:
    path: /admin/{id}/supProject
    controller: App\Controller\DashboardController::suppProjectAction

skillAdmin:
    path: /admin/skill
    controller: App\Controller\DashboardController::skillAction